<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="header">
    <h1>{{ $title }}</h1>
    <p>Date: {{ $date }}</p>
</div>

<h2>User Purchases</h2>
<table>
    <thead>
    <tr>
        <th>Purchase Code</th>
        <th>User ID</th>
        <th>Total Items</th>
        <th>Total Cost</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($purchases->whereNotNull('user_id') as $purchase)
        <tr>
            <td>{{ $purchase->purchase_code }}</td>
            <td>{{ $purchase->user_id }}</td>
            <td>{{ $purchase->items->count() }}</td>
            <td>
                {{ number_format($purchase->items->sum(function ($item) {
                    return $item->quantity * $item->price;
                }), 2) }} UAH
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

<h2>Guest Purchases</h2>
<table>
    <thead>
    <tr>
        <th>Purchase Code</th>
        <th>Total Items</th>
        <th>Total Cost</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($purchases->whereNull('user_id') as $purchase)
        <tr>
            <td>{{ $purchase->purchase_code }}</td>
            <td>{{ $purchase->items->count() }}</td>
            <td>
                {{ number_format($purchase->items->sum(function ($item) {
                    return $item->quantity * $item->price;
                }), 2) }} UAH
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    <h3>Total Earnings: {{ number_format($totalEarnings, 2) }} UAH</h3>
    <p>Generated by MovieApp Admin</p>
</div>
</body>
</html>
